version: '3.8'

services:
  api:
    build: ./api
    image: kvdomingo/gpt-api:latest
    env_file: ./api/.env
    volumes:
      - ./api:/api

  ui:
    image: node:16-alpine
    working_dir: /app
    environment:
      NODE_ENV: development
    entrypoint:
      - /bin/sh
      - "-c"
      - "yarn install && exec yarn dev --host 0.0.0.0 --port 3000"
    volumes:
      - ./ui:/app

  proxy:
    image: bitnami/nginx:latest
    volumes:
      - ./proxy:/opt/bitnami/nginx/conf/server_blocks:ro
    environment:
      - NGINX_HTTP_PORT_NUMBER=8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kengpt.rule=Host(`kengpt.localhost`)"
      - "traefik.http.routers.kengpt.entrypoints=http"
      - "traefik.docker.network=gateway"
      - "traefik.http.services.kengpt.loadbalancer.server.port=8000"
    networks:
      - default
      - gateway
    restart: unless-stopped

networks:
  gateway:
    external: true
